マップ作成ルールを改正
KPC-U16/CHaserRuleGuide-Pub pull request #1
Opened 2022-09-14 13:31 UTC by noko1024

マップ作成ルールについて以下の項目を追加しました
1. サイズは15マスx17マス または 21マスx17マス を用いる
2. マップ最外周にはブロックを設置しない
3. 各エージェントの出現位置を0マスとして、縦軸9マスの範囲にはブロックを設置しない

2022-09-14 15:13 UTC, umiwatarin reviewed
齟齬が消えたことは確認できました（Approveは精査した後に）

2022-09-16 02:54 UTC, umiwatarin requested changes
「縦軸9マス目」→「上下方向の9マス目にあたる2つのマス」

2022-09-16 03:07 UTC, umiwatarin reviewed
横方向9マス目ってどういう議決でブロック設置可になりましたっけ？

2022-09-16 10:44 UTC, noko1024 commented
旭川U-16のレギュレーションをベースにしているためです。
当該レギュレーションは横軸の制限をかけていないため、
独自に設定してしまうと参加者のプログラムが全道大会で適切に動作しない可能性があります。

2022-09-16 10:48 UTC, noko1024 commented
> 「縦軸9マス目」→「上下方向の9マス目にあたる2つのマス」 自機から見て上と下にそれぞれ該当する位置があることを明示したほうがよいと思います。

**各エージェントの出現位置を0マスとして、上下方向9マス目にはブロックを設置しない**でいかがでしょうか？

2022-09-16 11:28 UTC, yugu0202 commented
どちらか片方がマップ範囲外になるはずなのでその表記だと多少の誤解を生む気が…

2022-09-16 14:09 UTC, umiwatarin commented
「上下9マス目のどちらかのマスには通路またはアイテムが配置されなければならない」とかでどうでしょう

2022-09-20 23:59 UTC, noko1024 commented
> どちらか片方がマップ範囲外になるはずなのでその表記だと多少の誤解を生む気が…

各エージェントの出現位置を0マスとして、上下方向9マス目にはブロックを設置しない
ただし、フィールド外の領域の壁は除くものとする

でいかがでしょうか？

2022-09-23 15:14 UTC, umiwatarin approved these changes

2022-09-23 15:18 UTC, polyacetal approved these changes
LGTM

2022-09-23 15:22 UTC, merged