再試合する場合としない場合で整理
KPC-U16/CHaserRuleGuide-Pub pull request #13
Opened 2024-11-16 03:50 UTC by umiwatarin

2024-11-16 04:15 UTC, arumino-om approved these changes

2024-11-17 01:53 UTC, no1fushi approved these changes

2024-11-17 02:06 UTC, noko1024 commented on docs/index.md
> -2. 1-4の条件1-dに該当し、審判に依って再試合を実施しないと判断した場合、エージェントの自滅として扱う
この定義は削除してしまうと、取り扱いが不明になりませんか？
特に審判がエラーと認めた場合について

2024-11-17 05:22 UTC, umiwatarin commented on docs/index.md
> -2. 1-4の条件1-dに該当し、審判に依って再試合を実施しないと判断した場合、エージェントの自滅として扱う
`4. 再試合を行わない場合、その試合の結果は1-3に従う `
この規定によって充足できるかと思ったのですがいかがでしょうか？

2024-11-17 06:20 UTC, noko1024 requested changes

2024-11-17 06:20 UTC, noko1024 commented on docs/index.md
> -2. 1-4の条件1-dに該当し、審判に依って再試合を実施しないと判断した場合、エージェントの自滅として扱う
例外として
`対戦相手が明らかに意図的なエラーが起こるプログラムを実行した場合`
`その他に審判員および運営が相手のクライアントの異常を認めた場合`
のいずれかは審判が再試合するか否か決定してもいいよ
(逆に原則として、再試合は実施する)
という体系で書かれているので充足は出来ないと思います

2024-11-17 07:44 UTC, noko1024 approved these changes

2024-11-17 07:51 UTC, merged